config/routes.rb
PhotoShare::Application.routes.draw do

  root :to => 'photos#index', :via => :get

  match '/photos'         => 'photos#index',      :as => :photos,         :via => :get
  match '/photos/:id'     => 'photos#show',       :as => :photo,          :via => :get
  match '/uploads'        => 'uploads#index',     :as => :uploads,        :via => :get
  match '/uploads/:id'    => 'uploads#show',      :as => :upload,         :via => :get

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :exif_createdate, :exif_gpsaltitude, :exif_gpslatitude, :exif_gpslongitude, :filename

  belongs_to :upload

  def timestamp
  	
  	if exif_createdate != nil then
  		return exif_createdate
  	else
  		return upload.datesent
  	end

  end

end

app/models/upload.rb
class Upload < ActiveRecord::Base
  attr_accessible :datesent, :message_UID, :sender, :subject

  has_many :photos

  def teamname
    subject_p.strip!
    col_pos = subject_p.index(":")
    if col_pos == nil or col_pos == 0 then return " - no team - " end
    return subject_p[0 ... col_pos].strip
  end

  def photo_subject
    subject_p.strip!
    col_pos = subject_p.index(":")
    if col_pos == nil or col_pos == subject_p.length then return " - no subject - " end
    
    return subject_p[col_pos+1 ... subject_p.length].strip
  end


  def subject_p
     result = subject
     if (PhotoShareConfig.config['msg_prefix_pattern'] != "") then
         pattern = Regexp.new(PhotoShareConfig.config['msg_prefix_pattern'])
         result = subject.gsub(pattern, "")
     end
     return result.strip
   end

   def sender_name
      sender.strip!
      first_angle = sender.index("<")
      if (first_angle == nil || first_angle == 0) then return self.sender_email end
      return sender[0, first_angle].strip;
   end
   
   def sender_email
      sender.strip!
      first_angle = sender.index("<")
      second_angle = sender.index(">")
      if first_angle == nil then return sender end
      return sender[(first_angle+1) ... (second_angle)].strip
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    #@photos = @photos.sort_by &:timestamp
    @photos.sort! { |b,a| a.timestamp <=> b.timestamp }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(params[:upload])

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'Upload was successfully created.' }
        format.json { render json: @upload, status: :created, location: @upload }
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoShare</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1><%= PhotoShareConfig.config["sitetitle"] %></h1>

<%= link_to "Uploads", uploads_path %> | 
<%= link_to "Photos", photos_path %> 

<hr />

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br />
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :exif_createdate %><br />
    <%= f.text_field :exif_createdate %>
  </div>
  <div class="field">
    <%= f.label :exif_gpsaltitude %><br />
    <%= f.text_field :exif_gpsaltitude %>
  </div>
  <div class="field">
    <%= f.label :exif_gpslatitude %><br />
    <%= f.text_field :exif_gpslatitude %>
  </div>
  <div class="field">
    <%= f.label :exif_gpslongitude %><br />
    <%= f.text_field :exif_gpslongitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<div class="gallery">

<h1>Photos</h1>
<br />


<% @photos.each do |photo| %>
  
  <div class="photo">
      <ul class="metadata">
         <li class="caption"><b><%= photo.upload.subject_p %></b></li>
         <li class="caption"><%= mail_to photo.upload.sender_email, photo.upload.sender_name, :subject => "re: #{photo.upload.subject}" %></li>
         <li class="caption"><%= photo.timestamp.in_time_zone("Brisbane").strftime("%l:%M %P (%m/%d/%Y)") %></li>
      </ul>

      <%= link_to image_tag("/uploads/thumb_#{photo.filename}", :title => photo.upload.subject_p, :class => "photolink"), 
      photo_path(photo.id)   %>



  </div>

<% end %>
</div>

app/views/photos/map.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>

    <script type="text/javascript"
      src="http://maps.googleapis.com/maps/api/js?key=AIzaSyC8_ckQsG0Fufu1cQ7DZpxgdS4pH8tf918&sensor=true">
    </script>
    
    <script type="text/javascript">
      function initialize() {
      	
        var mapOptions = {
          center: new google.maps.LatLng(-34.397, 150.644),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map_canvas"),
            mapOptions);
      }
    </script>

  </head>

  <body onload="initialize()">
    <div id="map_canvas" style="width:100%; height:100%"></div>
  </body>

</html>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

[<%= link_to 'View Full Size', "/uploads/#{@photo.filename}"  %> ]
<br />
<%= image_tag "/uploads/medium_#{@photo.filename}" %>

<hr />

<p>
  <b>Filename:</b>
  <%= @photo.filename %>
</p>

<p>
  <b>Exif createdate:</b>
  <%= @photo.exif_createdate %>
</p>

<p>
  <b>Exif gpsaltitude:</b>
  <%= @photo.exif_gpsaltitude %>
</p>

<p>
  <b>Exif gpslatitude:</b>
  <%= @photo.exif_gpslatitude %>
</p>

<p>
  <b>Exif gpslongitude:</b>
  <%= @photo.exif_gpslongitude %>
</p>

app/views/uploads/_form.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message_UID %><br />
    <%= f.number_field :message_UID %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :datesent %><br />
    <%= f.datetime_select :datesent %>
  </div>
  <div class="field">
    <%= f.label :sender %><br />
    <%= f.text_field :sender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uploads/edit.html.erb
<h1>Editing upload</h1>

<%= render 'form' %>

<%= link_to 'Show', @upload %> |
<%= link_to 'Back', uploads_path %>

app/views/uploads/index.html.erb
<h1>Listing uploads</h1>

<hr />
<% @uploads.each do |upload| %>
  <h4>
    <%= upload.subject %> - <%= upload.sender %> - <%= upload.datesent %>
  </h3>
  <% upload.photos.each do | photo | %>
    <%= link_to image_tag("/uploads/thumb_#{photo.filename}"), 
      photo_path(photo.id)   %>
  <% end %>
  ( <%= upload.message_UID %> )
  <hr />
<% end %>

app/views/uploads/new.html.erb
<h1>New upload</h1>

<%= render 'form' %>

<%= link_to 'Back', uploads_path %>

app/views/uploads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Message uid:</b>
  <%= @upload.message_UID %>
</p>

<p>
  <b>Subject:</b>
  <%= @upload.subject %>
</p>

<p>
  <b>Datesent:</b>
  <%= @upload.datesent %>
</p>

<p>
  <b>Sender:</b>
  <%= @upload.sender %>
</p>